//영상
var moveArray = [['a','apple.png','apple--_us_1.mp3'],
	['a','ant.png','ant--_us_1.mp3'],
	['a','ax.png','ax--_us_1.mp3'],
	['b','baby.png','baby--_us_1.mp3'],
	['b','box.png','box--_us_1.mp3'],
	['b','boy.png','boy--_us_1.mp3'],
	['c','cake.png','cake--_us_1.mp3'],
	['c','cow.png','cow--_us_1.mp3'],
	['c','cup.png','cup--_us_1.mp3'],
	['d','dog.png','dog--_us_1.mp3'],
	['d','doll.png','doll--_us_1.mp3'],
	['d','duck.png','duck--_us_1.mp3'],
	['e','egg.png','egg--_us_1.mp3'],
	['e','elephant.png','elephant--_us_1.mp3'],
	['e','envelope.png','envelope--_us_1.mp3'],
	['f','fish.png','fish--_us_1.mp3'],
	['f','football.png','football--_us_1.mp3'],
	['f','fork.png','fork--_us_1.mp3'],
	['g','girl.png','girl--_us_1.mp3'],
	['g','goat.png','goat--_us_1.mp3'],
	['g','gorilla.png','gorilla--_us_1.mp3'],
	['h','ham.png','ham--_us_1.mp3'],
	['h','hat.png','hat--_us_1.mp3'],
	['h','hen.png','hen--_us_1.mp3'],
	['i','igloo.png','igloo--_us_1.mp3'],
	['i','ink.png','ink--_us_1.mp3'],
	['i','insect.png','insect--_us_1.mp3'],
	['j','jeep.png','jeep--_us_1.mp3'],
	['j','jet.png','jet--_us_1.mp3'],
	['j','juice.png','juice--_us_1.mp3'],
	['k','kangaroo.png','kangaroo--_us_1.mp3'],
	['k','king.png','king--_us_1.mp3'],
	['k','kiwi.png','kiwi--_us_1.mp3'],
	['l','lamp.png','lamp--_us_1.mp3'],
	['l','leg.png','leg--_us_1.mp3'],
	['l','lion.png','lion--_us_1.mp3'],
	['m','man.png','man--_us_1.mp3'],
	['m','milk.png','milk--_us_1.mp3'],
	['m','monkey.png','monkey--_us_1.mp3'],
	['n','nest.png','nest--_us_1.mp3'],
	['n','nose.png','nose--_us_1.mp3'],
	['n','nut.png','nut--_us_1.mp3'],
	['o','octopus.png','octopus--_us_1.mp3'],
	['o','ostrich.png','ostrich--_us_1.mp3'],
	['o','ox.png','ox--_us_1.mp3'],
	['p','pen.png','pen--_us_1.mp3'],
	['p','pig.png','pig--_us_1.mp3'],
	['p','pizza.png','pizza--_us_1.mp3'],
	['q','queen.png','queen--_us_1.mp3'],
	['q','question.png','question--_us_1.mp3'],
	['q','quilt.png','quilt--_us_1.mp3'],
	['r','rabbit.png','rabbit--_us_1.mp3'],
	['r','ruler.png','ruler--_us_1.mp3'],
	['r','run.png','run--_us_1.mp3'],
	['s','seed.png','seed--_us_1.mp3'],
	['s','six.png','six--_us_1.mp3'],
	['s','sun.png','sun--_us_1.mp3'],
	['t','tent.png','tent--_us_1.mp3'],
	['t','tiger.png','tiger--_us_1.mp3'],
	['t','turtle.png','turtle--_us_1.mp3'],
	['u','umbrella.png','umbrella--_us_1.mp3'],
	['u','uncle.png','uncle--_us_1.mp3'],
	['u','up.png','up--_us_1.mp3'],
	['v','van.png','van--_us_1.mp3'],
	['v','vase.png','vase--_us_1.mp3'],
	['v','violin.png','violin--_us_1.mp3'],
	['w','watch.png','watch--_us_1.mp3'],
	['w','water.png','water--_us_1.mp3'],
	['w','window.png','window--_us_1.mp3'],
	['x','watch.png','watch--_us_1.mp3'],
	['x','water.png','water--_us_1.mp3'],
	['x','window.png','window--_us_1.mp3'],
	['y','box.png','box--_us_1.mp3'],
	['y','six.png','six--_us_1.mp3'],
	['y','ox.png','ox--_us_1.mp3'],
	['z','zebra.png','zebra--_us_1.mp3'],
	['z','zero.png','zero--_us_1.mp3'],
	['z','zipper.png','zipper--_us_1.mp3']
];


var isoCode = [
	['Afghanistan','AF'],
	['Aland Islands','AX'],
	['Albania','AL'],
	['Algeria','DZ'],
	['American Samoa','AS'],
	['Andorra','AD'],
	['Angola','AO'],
	['Anguilla','AI'],
	['Antarctica','AQ'],
	['Antigua and Barbuda','AG'],
	['Argentina','AR'],
	['Armenia','AM'],
	['Aruba','AW'],
	['Australia','AU'],
	['Austria','AT'],
	['Azerbaijan','AZ'],
	['Bahamas','BS'],
	['Bahrain','BH'],
	['Bangladesh','BD'],
	['Barbados','BB'],
	['Belarus','BY'],
	['Belgium','BE'],
	['Belize','BZ'],
	['Benin','BJ'],
	['Bermuda','BM'],
	['Bhutan','BT'],
	['Bolivia, Plurinational State of','BO'],
	['Bonaire, Sint Eustatius and Saba','BQ'],
	['Bosnia and Herzegovina','BA'],
	['Botswana','BW'],
	['Bouvet Island','BV'],
	['Brazil','BR'],
	['British Indian Ocean Territory','IO'],
	['Brunei Darussalam','BN'],
	['Bulgaria','BG'],
	['Burkina Faso','BF'],
	['Burundi','BI'],
	['Cambodia','KH'],
	['Cameroon','CM'],
	['Canada','CA'],
	['Cape Verde','CV'],
	['Cayman Islands','KY'],
	['Central African Republic','CF'],
	['Chad','TD'],
	['Chile','CL'],
	['China','CN'],
	['Christmas Island','CX'],
	['Cocos (Keeling) Islands','CC'],
	['Colombia','CO'],
	['Comoros','KM'],
	['Congo','CG'],
	['Congo, the Democratic Republic of the','CD'],
	['Cook Islands','CK'],
	["Costa Rica",'CR'],
	["Cote d'Ivoire",'CI'],
	['Croatia','HR'],
	['Cuba','CU'],
	['Curacao','CW'],
	['Cyprus','CY'],
	['Czech Republic','CZ'],
	['Denmark','DK'],
	['Djibouti','DJ'],
	['Dominica','DM'],
	['Dominican Republic','DO'],
	['Ecuador','EC'],
	['Egypt','EG'],
	['El Salvador','SV'],
	['Equatorial Guinea','GQ'],
	['Eritrea','ER'],
	['Estonia','EE'],
	['Ethiopia','ET'],
	['Falkland Islands (Malvinas)','FK'],
	['Faroe Islands','FO'],
	['Fiji','FJ'],
	['Finland','FI'],
	['France','FR'],
	['French Guiana','GF'],
	['French Polynesia','PF'],
	['French Southern Territories','TF'],
	['Gabon','GA'],
	['Gambia','GM'],
	['Georgia','GE'],
	['Germany','DE'],
	['Ghana','GH'],
	['Gibraltar','GI'],
	['Greece','GR'],
	['Greenland','GL'],
	['Grenada','GD'],
	['Guadeloupe','GP'],
	['Guam','GU'],
	['Guatemala','GT'],
	['Guernsey','GG'],
	['Guinea','GN'],
	['Guinea-Bissau','GW'],
	['Guyana','GY'],
	['Haiti','HT'],
	['Heard Island and McDonald Islands','HM'],
	['Holy See (Vatican City State)','VA'],
	['Honduras','HN'],
	['Hong Kong','HK'],
	['Hungary','HU'],
	['Iceland','IS'],
	['India','IN'],
	['Indonesia','ID'],
	['Iran, Islamic Republic of','IR'],
	['Iraq','IQ'],
	['Ireland','IE'],
	['Isle of Man','IM'],
	['Israel','IL'],
	['Italy','IT'],
	['Jamaica','JM'],
	['Japan','JP'],
	['Jersey','JE'],
	['Jordan','JO'],
	['Kazakhstan','KZ'],
	['Kenya','KE'],
	['Kiribati','KI'],
	["Korea, Democratic People's Republic of",'KP'],
	['Korea, Republic of','KR'],
	['Kuwait','KW'],
	['Kyrgyzstan','KG'],
	["Lao People's Democratic Republic",'LA'],
	['Latvia','LV'],
	['Lebanon','LB'],
	['Lesotho','LS'],
	['Liberia','LR'],
	['Libya','LY'],
	['Liechtenstein','LI'],
	['Lithuania','LT'],
	['Luxembourg','LU'],
	['Macao','MO'],
	['Macedonia, the Former Yugoslav Republic of','MK'],
	['Madagascar','MG'],
	['Malawi','MW'],
	['Malaysia','MY'],
	['Maldives','MV'],
	['Mali','ML'],
	['Malta','MT'],
	['Marshall Islands','MH'],
	['Martinique','MQ'],
	['Mauritania','MR'],
	['Mauritius','MU'],
	['Mayotte','YT'],
	['Mexico','MX'],
	['Micronesia, Federated States of','FM'],
	['Moldova, Republic of','MD'],
	['Monaco','MC'],
	['Mongolia','MN'],
	['Montenegro','ME'],
	['Montserrat','MS'],
	['Morocco','MA'],
	['Mozambique','MZ'],
	['Myanmar','MM'],
	['Namibia','NA'],
	['Nauru','NR'],
	['Nepal','NP'],
	['Netherlands','NL'],
	['New Caledonia','NC'],
	['New Zealand','NZ'],
	['Nicaragua','NI'],
	['Niger','NE'],
	['Nigeria','NG'],
	['Niue','NU'],
	['Norfolk Island','NF'],
	['Northern Mariana Islands','MP'],
	['Norway','NO'],
	['Oman','OM'],
	['Pakistan','PK'],
	['Palau','PW'],
	['Palestine, State of','PS'],
	['Panama','PA'],
	['Papua New Guinea','PG'],
	['Paraguay','PY'],
	['Peru','PE'],
	['Philippines','PH'],
	['Pitcairn','PN'],
	['Poland','PL'],
	['Portugal','PT'],
	['Puerto Rico','PR'],
	['Qatar','QA'],
	['Reunion','RE'],
	['Romania','RO'],
	['Russian Federation','RU'],
	['Rwanda','RW'],
	['Saint Barthelemy','BL'],
	['Saint Helena, Ascension and Tristan da Cunha','SH'],
	['Saint Kitts and Nevis','KN'],
	['Saint Lucia','LC'],
	['Saint Martin (French part)','MF'],
	['Saint Pierre and Miquelon','PM'],
	['Saint Vincent and the Grenadines','VC'],
	['Samoa','WS'],
	['San Marino','SM'],
	['Sao Tome and Principe','ST'],
	['Saudi Arabia','SA'],
	['Senegal','SN'],
	['Serbia','RS'],
	['Seychelles','SC'],
	['Sierra Leone','SL'],
	['Singapore','SG'],
	['Sint Maarten (Dutch part)','SX'],
	['Slovakia','SK'],
	['Slovenia','SI'],
	['Solomon Islands','SB'],
	['Somalia','SO'],
	['South Africa','ZA'],
	['South Georgia and the South Sandwich Islands','GS'],
	['South Sudan','SS'],
	['Spain','ES'],
	['Sri Lanka','LK'],
	['Sudan','SD'],
	['Suriname','SR'],
	['Svalbard and Jan Mayen','SJ'],
	['Swaziland','SZ'],
	['Sweden','SE'],
	['Switzerland','CH'],
	['Syrian Arab Republic','SY'],
	['Taiwan, Province of China','TW'],
	['Tajikistan','TJ'],
	['Tanzania, United Republic of','TZ'],
	['Thailand','TH'],
	['Timor-Leste','TL'],
	['Togo','TG'],
	['Tokelau','TK'],
	['Tonga','TO'],
	['Trinidad and Tobago','TT'],
	['Tunisia','TN'],
	['Turkey','TR'],
	['Turkmenistan','TM'],
	['Turks and Caicos Islands','TC'],
	['Tuvalu','TV'],
	['Uganda','UG'],
	['Ukraine','UA'],
	['United Arab Emirates','AE'],
	['United Kingdom','GB'],
	['United States','US'],
	['United States Minor Outlying Islands','UM'],
	['Uruguay','UY'],
	['Uzbekistan','UZ'],
	['Vanuatu','VU'],
	['Venezuela, Bolivarian Republic of','VE'],
	['Viet Nam','VN'],
	['Virgin Islands, British','VG'],
	['Virgin Islands, U.S.','VI'],
	['Wallis and Futuna','WF'],
	['Western Sahara','EH'],
	['Yemen','YE'],
	['Zambia','ZM'],
	['Zimbabwe','ZW']
	];

var dMonth = [
	["January","1"],
	["February","2"],
	["March","3"],
	["April","4"],
	["May","5"],
	["June","6"],
	["July","7"],
	["August","8"],
	["September","9"],
	["October","10"],
	["November","11"],
	["December","12"]
];